[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "openai>=2.14.0",
    "streamlit>=1.52.2",
    "tenacity>=9.1.2",
]
